name: Action Usage

on:
  push:

jobs:
  get_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Get Branch Name
      id: extract_branch
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/} | sed -nE 's#.*?([a-zA-Z]{3}-[0-9]{0,5})$#\1#p')" >> $GITHUB_OUTPUT
    
  action_usage:
    runs-on: ubuntu-latest
    needs: get_branch
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: list
      run: |
        echo ${{ needs.get_branch.outputs.branch }}
        ls -la ${PWD}
    - id: action_step
      name: Action Step
      uses: ./actions/action@${{ needs.get_branch.outputs.branch }}
