name: Action Usage

on:
  push:

jobs:
  action-usage:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Get Branch Name
      id: extract_branch
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      
    - name: list
      run: |
        ls -la ${PWD}
    - id: action_step
      name: Action Step
      uses: ./actions/action
      with:
        branch_name: ${{ steps.extract_branch.outputs.branch }}
