name: Action Usage

on:
  push:

jobs:
  action-usage:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: list
      run: |
        ls -la ${PWD}
    - id: action_step
      name: Action Step
      uses: ./actions/action@${GITHUB_REF#refs/heads/}
