name: Create Release
 
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

permissions: write-all

jobs:
  create-release:
    if: ${{ github.ref == 'refs/heads/master'}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create GitHub Release and Tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ inputs.tag }}
        release_name: ${{ inputs.tag }}

  # create_tag:
  #   runs-on: ubuntu-latest
  #   permissions: write-all 
  #   steps:
  #     - name: Create tag
  #       id: tag
  #       uses: actions/github-script@v5
  #       with:
  #         script: |
  #           github.rest.git.createRef({
  #             owner: context.repo.owner,
  #             repo: context.repo.repo,
  #             ref: 'refs/tags/${{ inputs.tag }}',
  #             sha: context.sha
  #           })
  # create_release:
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - create_tag
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Create GitHub Release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ inputs.tag }}
  #         release_name: Release ${{ inputs.tag }}
          # body: |
          #   It's been created from ${{ github.job }}
