name: Create Release
 
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Desired tag
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: ${{input.tag}}
        uses: actions/github-tag-action@v6.1
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: | 
            TAG: ${{inputs.tag}}
            REF: ${{inputs.ref}}
