name: Create Release
 
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Desired tag
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release and Tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{inputs.tag}}
          release_name: ${{inputs.ref}}
          body_path: | 
           TAG: ${{inputs.tag}}
           REF: ${{inputs.ref}}
