name: Uninstall

on:
  pull_request:
    types: [ closed ]


# bogus  

jobs:
  on_closed_pr:
    #if: ${{ (github.event_name == 'delete') }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo '${{ (github.ref) }} ${{ (github.event_name) }} ${{ github.event.action }}' >> $GITHUB_STEP_SUMMARY
        echo "Runs on closed PR" >> $GITHUB_STEP_SUMMARY
