name: Run On Pipeline

on:
  push:
  pull_request:
#   pull_request:
#     types: [ closed ]
#     branches-ignore:
#     - master

jobs:
  on_closed_pr:
    #if: ${{ (github.event_name == 'delete') }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo '${{ (github.event_name) }}' >> $GITHUB_STEP_SUMMARY
        echo "Runs on closed PR" >> $GITHUB_STEP_SUMMARY
