name: Run On Pipeline

on:
  pull_request:
    types:
    - closed
    branches-ignore:
    - '*master*'

jobs:
  on_pr:
    #if: ${{ (github.event_name == 'delete') }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo '${{ github.event_name }} was ${{ github.event.action }}' >> $GITHUB_STEP_SUMMARY
        echo "custom branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_STEP_SUMMARY
        echo "branch=${GITHUB_REF}" >> $GITHUB_STEP_SUMMARY
        echo "head_ref=${GITHUB_HEAD_REF}" >> $GITHUB_STEP_SUMMARY
    # echo "Runs on closed PR" >> $GITHUB_STEP_SUMMARY
    
  on_closed_pr:
    #if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-lateste
    steps:
    - run: |
        echo '${{ github.event_name }} was ${{ github.event.action }}' >> $GITHUB_STEP_SUMMARY
        echo "custom branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_STEP_SUMMARY
        echo "branch=${GITHUB_REF}" >> $GITHUB_STEP_SUMMARY
        echo "head_ref=${GITHUB_HEAD_REF}" >> $GITHUB_STEP_SUMMARY
# bogus
