name: Uninstall Branch

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: branch name
        required: true

jobs:
  updated-changelog:
    runs-on: ubuntu-latest
    outputs: updated
    steps:
    - run: |
        if [[ git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep "CHANGELOG" ]]; then
          echo "updated=true" >> $GITHUB_OUTPUT
        else
          echo "updated=false" >> $GITHUB_OUTPUT
        fi

  show-inputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "input: ${{ inputs.branch-name }}"
