name: Uninstall Branch

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: branch name
        required: true

jobs:
  updated-changelog:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.changelog-update.outputs.updated }}
    steps:
    - name: Is CHANGELOG updated
      id: changelog-update
      run: |
        if [[ $(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep "CHANGELOG") ]]; then
          echo "updated='true'" >> $GITHUB_OUTPUT
        else
          echo "updated='false'" >> $GITHUB_OUTPUT
          # exit 1
        fi

  show-inputs:
    runs-on: ubuntu-latest
    needs: updated-changelog
    #if: ${{ needs.updated-changelog.outputs.updated=='true' }}
    steps:
    - run: |
        echo "input: ${{ inputs.branch-name }}"
    - uses: actions/checkout@v4
    - run: |
        echo $HOME
        ls -la ../../*/*/*
    - uses: ./.github/actions/the_action/
      with:
        branch-name: |
          line from show input
          line from inputs ${{ inputs.branch-name }}
