name: Uninstall Branch

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: branch name
        required: true

jobs:
  show-inputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "input: ${{ inputs.branch-name }}"
